/**
 * Generate TypeScript declarations from the briks on disk.
 *
 * The types come from the same inferred schemas that validate pages, so they
 * cannot drift from the markup: rename a prop inside a `.brix` file and every
 * page still passing the old name is flagged by `svelte-check` and by the
 * editor, without anything else being touched.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { toComponentName, type PropSchema } from '@brixter/core';
import type { BrikRegistry } from './briks.ts';

/** Write the declaration file, skipping the write when nothing changed. */
export function writeGeneratedTypes(registry: BrikRegistry, target: string): void {
	const source = generateTypes(registry);
	try {
		if (readFileSync(target, 'utf-8') === source) return;
	} catch {
		// No file yet — fall through and write it.
	}
	mkdirSync(path.dirname(target), { recursive: true });
	writeFileSync(target, source);
}

export function generateTypes(registry: BrikRegistry): string {
	const briks = registry.all();
	const lines: string[] = [
		'// Generated by brixter. Do not edit — it is rewritten from the `.brix`',
		'// files whenever one of them changes.',
		'',
		'declare module •brixter/generated• {'
	];

	const entries: string[] = [];

	for (const brik of briks) {
		const name = toComponentName(brik.name);
		if (!brik.definition) {
			lines.push(
				`\t/** ${name} is a hand-written Svelte brik — its props are not inferred. */`,
				`\texport type ${name}Props = Record<string, unknown>;`,
				''
			);
			entries.push(`\t\t${name}: ${name}Props;`);
			continue;
		}

		const { schema } = brik.definition;
		if (schema.description) lines.push(`\t/** ${schema.description} */`);
		lines.push(`\texport interface ${name}Props ${renderFields(schema.props, 1)}`, '');
		entries.push(`\t\t${name}: ${name}Props;`);
	}

	lines.push(
		'\t/** Every brik on this site, by the `type` a page writes. */',
		'\texport interface BrikProps {',
		...(entries.length > 0 ? entries : ['\t\t[type: string]: Record<string, unknown>;']),
		'\t}',
		'',
		'\texport type BrikEntry = {',
		'\t\t[Type in keyof BrikProps]: { type: Type; props?: BrikProps[Type] };',
		'\t}[keyof BrikProps];',
		'',
		'\t/** The frontmatter of a `+page.md`. */',
		'\texport interface PageFrontmatter {',
		'\t\tmetadata?: Record<string, unknown>;',
		'\t\tlayout?: string;',
		'\t\taliases?: Array<string | { path?: string; from?: string; status?: number }>;',
		'\t\tsitemap?: false | { loc?: string; lastmod?: string; changefreq?: string; priority?: number };',
		'\t\tbrix?: BrikEntry[];',
		'\t}',
		'}',
		''
	);

	return lines.join('\n').replaceAll('•', "'");
}

function renderFields(fields: Record<string, PropSchema>, depth: number): string {
	const indent = '\t'.repeat(depth);
	const inner = '\t'.repeat(depth + 1);
	const lines: string[] = ['{'];

	for (const [key, field] of Object.entries(fields)) {
		const doc = describe(field);
		if (doc) lines.push(`${inner}/** ${doc} */`);
		lines.push(
			`${inner}${propertyName(key)}${field.required ? '' : '?'}: ${render(field, depth + 1)};`
		);
	}

	lines.push(`${indent}}`);
	return lines.join('\n');
}

function render(field: PropSchema, depth: number): string {
	switch (field.type) {
		case 'number':
			return 'number';
		case 'boolean':
			return 'boolean';
		case 'enum':
			return (field.options ?? []).map((option) => JSON.stringify(option)).join(' | ') || 'string';
		case 'json':
			return 'unknown';
		case 'object':
			return renderFields(field.fields ?? {}, depth);
		case 'array':
			return field.items ? `Array<${render(field.items, depth)}>` : 'unknown[]';
		default:
			return 'string';
	}
}

/** A one-line doc comment: the label, plus anything the annotations added. */
function describe(field: PropSchema): string {
	const notes: string[] = [field.label];
	if (field.default !== undefined) notes.push(`default: ${summarize(field.default)}`);
	if (field.min !== undefined) notes.push(`min: ${field.min}`);
	if (field.max !== undefined) notes.push(`max: ${field.max}`);
	if (field.pattern) notes.push(`pattern: ${summarize(field.pattern)}`);
	return notes.filter(Boolean).join(' — ');
}

/**
 * A default value rendered for a doc comment: short enough to read, and unable
 * to close the comment. An inline `<svg>` placeholder is a perfectly ordinary
 * default and would otherwise fill the line.
 */
function summarize(value: unknown): string {
	const text = JSON.stringify(value) ?? '';
	const trimmed = text.length > 60 ? `${text.slice(0, 57)}…"` : text;
	return trimmed.replaceAll('*/', '*\\/');
}

function propertyName(key: string): string {
	return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}
